services:
  reviews:
    container_name: reviewsService
    build: ./
    depends_on:
      - testingamqp
      - testingdb

  testingamqp:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/data"

  testingdb:
    image: postgres:16
    container_name: TestingDB
    hostname: ${POSTGRES_HOST}
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  rabbitmq_data: