rabbitmq_user = "admin"
rabbitmq_pass = "admin"
rabbitmq_host = "localhost"
rabbitmq_port = "5672"

postgres_user = "postgres"
postgres_pass = "postgres"
postgres_host = "localhost"
postgres_port = "5432"
postgres_db = "reviews_testing"
postgres_ssl = "disable"
postgres_url = "postgres://postgres:postgres@localhost:5432/reviews?sslmode=disable"


